# pxe-setup.yml
# sets up the DHCP and TFTP servers for PXE booting Talos Linux
---
- name: Setup DHCP boot
  hosts: openwrt
  gather_facts: false
  tasks:
    - name: Include PXE server setup task
      ansible.builtin.include_role:
        name: router
        tasks_from: setup_dhcp_boot

- name: Setup TFTP server
  hosts: asuswrt
  gather_facts: false
  tasks:
    - name: Include server setup tasks
      ansible.builtin.include_role:
        name: router
        tasks_from: setup_pxe_server
    - name: Generate EFI URL
      ansible.builtin.include_role:
        name: talos
        tasks_from: get_image_urls
    - name: Download Secure Boot UKI image
      ansible.builtin.get_url:
        url: "{{ talos_efi_url }}"
        dest: "{{ router_tftp_root }}/boot.efi"
        mode: '0644'
        timeout: 60
