---
- name: Setup Talos Linux
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Activate Talos
      tags: [never]
      ansible.builtin.include_role:
        name: talos
        tasks_from: activate

    - name: Install ArgoCD
      ansible.builtin.include_role:
        name: argocd
