---
- name: Setup Talos Linux Master Node
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Generate worker config
      ansible.builtin.include_role:
        name: talos
        tasks_from: gen_worker_config
      vars: 
        talos_install_disk: /dev/nvme0n1
        talos_endpoint: "master"
        talos_hostname: "worker"

    - name: Activate worker node
      ansible.builtin.include_role:
        name: talos
        tasks_from: activate_worker
      vars: 
        talos_node_ip: "worker"
