---
- name: Update Talos Linux configuration
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Include Talos patch task
      ansible.builtin.include_role:
        name: talos
        tasks_from: patch
      loop:
        - labels.yaml
      loop_control:
        loop_var: talos_patch_file
