---
# [CAUTION] Wipe system partitions while keep user partitions data
- name: Reset Talos Linux to maintainance mode
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Include Talos reset tasks
      ansible.builtin.include_role:
        name: talos
        tasks_from: reset
