---
# [CAUTION] Wipe system DISK including the Talos OS and user partitions.
- name: Format system disk
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Include Talos destroy task
      ansible.builtin.include_role:
        name: talos
        tasks_from: destroy.yml
