---
- name: Get Talos image url
  ansible.builtin.include_tasks: get_image_urls.yml

- name: Get Kubernetes version
  ansible.builtin.include_tasks: get_k8s_version.yml

- name: Ensure talos config directory exists
  ansible.builtin.file:
    path: "{{ talos_config_path }}"
    state: directory
    mode: '0700'

- name: Generate Talos secrets
  ansible.builtin.command:
    talosctl gen secrets --talos-version {{ talos_version }}
  args:
    chdir: "{{ talos_config_path }}"
    creates: secrets.yaml

- name: Encrypt secrets and backup to this repository
  community.sops.sops_encrypt:
    content_yaml: "{{ lookup('ansible.builtin.file', talos_config_path + '/secrets.yaml') | from_yaml }}"
    path: "{{ role_path }}/files/secrets.sops.yaml"
  when: lookup('ansible.builtin.env', 'SOPS_AGE_KEY') != ""

- name: Generate patches
  ansible.builtin.template:
    src: "config_partition.yaml.j2"
    dest: "{{ talos_config_path }}/config_partition.yaml"
    mode: "0600"

- name: Generate Talos config
  ansible.builtin.command: >
    talosctl gen config {{ talos_cluster_name }} https://{{ talos_node_ip }}:6443
    --config-patch-control-plane  @{{ role_path }}/files/config.yaml
    --config-patch-control-plane @config_partition.yaml
    --install-disk {{ talos_install_disk }}
    --install-image {{ talos_installer_url }}
    --kubernetes-version {{ talos_k8s_version }}
    --talos-version {{ talos_version }}
    --with-secrets secrets.yaml
    --force
  args:
    chdir: "{{ talos_config_path }}"

- name: Remove all comment lines from the YAML file
  ansible.builtin.replace:
    path: "{{ talos_config_path }}/controlplane.yaml"
    regexp: '^\s*#.*$'
    replace: ''

- name: Remove empty lines
  ansible.builtin.replace:
    path: "{{ talos_config_path }}/controlplane.yaml"
    regexp: '\n\s*\n'
    replace: '\n'

- name: Update talosconfig
  ansible.builtin.command: >
    talosctl --talosconfig=talosconfig config {{ config_key }} {{ talos_node_ip }}
  args:
    chdir: "{{ talos_config_path }}"
  loop_control:
    loop_var: config_key
  loop:
    - node
    - endpoint
