---
- name: Get Talos image url
  ansible.builtin.include_tasks: get_image_urls.yml

- name: Ensure talos config directory exists
  ansible.builtin.file:
    path: "{{ talos_config_path }}"
    state: directory
    mode: '0700'

- name: Generate patches
  ansible.builtin.template:
    src: "patch-hostname.yaml.j2"
    dest: "{{ talos_config_path }}/patch-hostname.yaml"
    mode: "0600"

- name: Generate Talos configs using in-memory secrets
  ansible.builtin.shell:
    cmd: >
      talosctl gen config {{ talos_cluster_name }} https://{{ talos_endpoint }}:6443
      --additional-sans {{ talos_endpoint }}
      --config-patch-worker @{{ role_path }}/files/patch-label-gpu.yaml
      --config-patch-worker @{{ role_path }}/files/patch-label-worker-role.yaml
      --config-patch-worker @{{ role_path }}/files/patch-worker-partition.yaml
      --config-patch-worker @patch-hostname.yaml
      --force
      --install-disk {{ talos_install_disk }}
      --install-image {{ talos_installer_url }}
      --output-types worker
      --talos-version {{ talos_version }}
      --with-cluster-discovery=false
      --with-examples=false
      --with-docs=false
      --with-secrets <(echo {{ lookup('ansible.builtin.file', role_path + '/files/secrets.sops.yaml') | community.sops.decrypt | quote }})
    executable: /bin/bash
    chdir: "{{ talos_config_path }}"
  # no_log: true
