---
- name: Get Talos image url
  ansible.builtin.include_tasks: get_image_urls.yml

- name: Ensure talos config directory exists
  ansible.builtin.file:
    path: "{{ talos_config_path }}"
    state: directory
    mode: '0700'

- name: Generate Talos secrets
  ansible.builtin.command:
    talosctl gen secrets --talos-version {{ talos_version }}
  args:
    chdir: "{{ talos_config_path }}"
    creates: secrets.yaml

- name: Encrypt secrets and backup to this repository
  community.sops.sops_encrypt:
    content_yaml: "{{ lookup('ansible.builtin.file', talos_config_path + '/secrets.yaml') | from_yaml }}"
    path: "{{ role_path }}/files/secrets.sops.yaml"
  when: lookup('ansible.builtin.env', 'SOPS_AGE_KEY') != ""

- name: Generate Talos config
  ansible.builtin.command: >
    talosctl gen config {{ talos_cluster_name }} https://{{ talos_endpoint }}:6443
    --config-patch-control-plane @{{ role_path }}/files/partition.yaml
    --install-disk {{ talos_install_disk }}
    --install-image {{ talos_installer_url }}
    --talos-version {{ talos_version }}
    --additional-sans {{ talos_endpoint }}
    --with-secrets secrets.yaml
    --with-examples=false
    --with-docs=false
    --force
  args:
    chdir: "{{ talos_config_path }}"


- name: Update talosconfig
  ansible.builtin.command: >
    talosctl --talosconfig=talosconfig config {{ config_key }} {{ talos_endpoint }}
  args:
    chdir: "{{ talos_config_path }}"
  loop_control:
    loop_var: config_key
  loop:
    # - node
    - endpoint
