---
- name: Generate raw secrets into memory
  ansible.builtin.command:
    cmd: talosctl gen secrets -o -
  register: talos_secrets_raw
  no_log: true

- name: Encrypt raw secrets and save to repository
  community.sops.sops_encrypt:
    content_yaml: "{{ talos_secrets_raw.stdout | from_yaml }}"
    path: "{{ role_path }}/files/secrets.sops.yaml"
  no_log: true