---
# Usage:
# - name: Update Talos
#   ansible.builtin.include_tasks: patch.yml
#   vars:
#     talos_patch_file: default_network.yaml.j2

- name: Apply config changes
  ansible.builtin.command:
    cmd: "talosctl patch machineconfig --patch {{ lookup('template', talos_patch_file) | from_yaml | to_json | quote }}"

