---
- name: Reset Talos to maintenance state (Keep user partitions)
  ansible.builtin.command: |
    talosctl reset \
    --graceful=false \
    --wipe-mode system-disk \
    --system-labels-to-wipe STATE \
    --system-labels-to-wipe EPHEMERAL \
    --reboot
