apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  diskSelector:
    match: disk.transport == 'sata' && !system_disk
  maxSize: 30GiB
---
apiVersion: v1alpha1
kind: UserVolumeConfig
name: longhorn
volumeType: partition
provisioning:
  diskSelector:
    match: disk.transport == 'sata' && !system_disk
  minSize: 100GiB
