---
- name: Create flux-system namespace
  kubernetes.core.k8s:
    name: flux-system
    kind: Namespace
    state: present

- name: Install flux CD
  environment:
    GITHUB_TOKEN: "{{ fluxcd_github_pat }}"
  ansible.builtin.command: |
    flux bootstrap github \
      --owner={{ fluxcd_github_user }} \
      --repository={{ fluxcd_github_repo }} \
      --path={{ fluxcd_github_path }} \
      --personal

- name: Deploy AGE key for FluxCD
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: sops-age
        namespace: flux-system
      stringData:
        age.agekey: "{{ lookup('env', 'SOPS_AGE_KEY') }}"

- name: Deploy initial config
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: init-config
        namespace: flux-system
      data:
        domain_name: "{{ fluxcd_domain_name }}"
        acme_email: "{{ fluxcd_acme_email }}"
