apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  diskSelector:
    match: disk.transport == 'sata'
  minSize: 20GiB
  maxSize: 30GiB
---
apiVersion: v1alpha1
kind: UserVolumeConfig
name: data
volumeType: partition
provisioning:
  diskSelector:
    match: disk.transport == 'sata'
  minSize: 200GiB
  maxSize: "-20GiB"
