# Apply by default
---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  maxSize: 200GiB
---
apiVersion: v1alpha1
kind: UserVolumeConfig
name: local-data
volumeType: partition
provisioning:
  diskSelector:
    match: disk.dev_path == '/dev/nvme0n1'
  minSize: 1000GiB
---
# Enable workers on your control plane nodes
cluster:
  allowSchedulingOnControlPlanes: true
---
# remove label when a load balancer such as MetalLB is used
machine:
  nodeLabels:
    node.kubernetes.io/exclude-from-external-load-balancers:
      $patch: delete
