# Create a empty new volume on the node. 
apiVersion: v1alpha1
kind: UserVolumeConfig
name: hdd-4g
provisioning:
  diskSelector:
    match: disk.dev_path == '/dev/sda' # use "talosctl get disks" for the exact selector
  minSize: 3000GiB
  grow: true
