---
- name: Config PXE/TFTP Host
  ansible.builtin.blockinfile:
    path: /etc/config/dhcp
    marker: "# {mark} ANSIBLE MANAGED DHCP BOOT #"
    block: |
      config boot
        option servername 'tftp_server'
        option filename 'boot.efi'
        option serveraddress '{{ router_server_ip }}'
  notify: Restart OpenWrt Dnsmasq
