talos_disk_passphrase: ENC[AES256_GCM,data:e9EH6gOkAEGIjk6TXzLQqhlwN842VWRWLYTRTm2J,iv:Qt2vRvLj05WQ+8ZxOlsokfNwQczOsNvagE5mxaNqAak=,tag:YfYMDCkdntErXUucaMHUZA==,type:str]
fluxcd_github_pat: ENC[AES256_GCM,data:3cPowXXOMfTAj3l8LRU+cjiOpuUhWm5/a8CpQHPfqNtBB6YXjVKVa5rrXFIynC5rEAY56urFZHCMqWVt/DajPtBxCx48P6en6SZIPB1dvQfcy1/5hAUCgCPaq6+A,iv:sskIv99DPkRMq50tYI2PCIyteEz8PVqtNmgi4jwJRAg=,tag:Bw4M4Ymqydnyo7q3PFwKag==,type:str]
sops:
    age:
        - recipient: age1nu7vf3mgwds705rpfnvzlr20zkphh0tga4hc06xs7nmrxwmnsyvsp8sxzc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLamJha2I4aEVubDZSaEx1
            NVlaeEJhVXlqQmlHSWgwZkJFdmxQcFFEeFQ0Ck1ROEhjZW10MWxFU0hYTmNheWpv
            SkRTc3Rtb08wdG9oTENRZWJYL0JnOHMKLS0tIHNSbnNmdmd6TFNRQnhFM21oV2tS
            ZUdJTWd0d08rYzFCbTVJRUpHZlZETVkK8lkvuaUvkqw+oiBDvPS3SDpV1G5/G+gy
            +laBSJdVHOO59esiZtEHLxg9Zu7zLgfIJsnOgTvvyprhFYgyPPVl3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-20T19:59:57Z"
    mac: ENC[AES256_GCM,data:IStXfI+726okZo4JPW64B+QY6/YvZw3bQ06qgYBhEpswUAhGHkuAtxnh5s1VIqCNJLc8AvgBLSBrhijIrs6aWixJeiyf41f/GRPqYvqkRBmIsfxt7GF138nzEBGKmhS24aRdCk4C1n6jruTELPFZfnlG7RAC2ZuQOlzf2ghOySU=,iv:e6ztjjCZPEwOPuajJXzSt6SPnvkz60syy9Q5TyZ7+d8=,tag:M6rYShM2h1x9/ExDz3GXDA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
