---
fluxcd_github_pat: ""
fluxcd_github_user: "23hp"
fluxcd_github_repo: "homelab-apps"
fluxcd_github_path: "clusters/immutableGate"

fluxcd_domain_name: "immutable-gate.com"
fluxcd_acme_email: "admin@immutable-gate.com"
