---
fluxcd_github_pat: ""
fluxcd_github_user: "23hp"
fluxcd_github_repo: "homelab-apps"
fluxcd_github_path: "clusters/immutableGate"

fluxcd_secret_repository_url: "https://github.com/23hp/immutable-gate-secret"
